query GroupPosts($groupId: Float!, $limit: Float!, $sortBy: String, $cursor: Float) {
  groupPosts(groupId: $groupId, limit: $limit, sortBy: $sortBy, cursor: $cursor) {
    posts {
      id
      createdAt
      updatedAt
      title
      body
      isDisabled
      voteCount
      wasEdited
      bodySnippet
      creator {
        errors {
          field
          message
        }
        user {
          id
          createdAt
          username
          isDisabled
          profileImgUrl
          email
        }
      }
    }
    hasMore
    cursor
  }
}